version: '3.3'
services:
    ws-to-wss-proxy:
        ports:
            - '8580:80'
        environment:
            - NGINX_PORT=80
        image: subramaniamnatarajan/ws-to-wss-proxy:latest
        build:
          context: ./